# Generated by Django 2.1.1 on 2018-11-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Introduction to Django')),
                ('idName', models.TextField(default='HELP-123')),
                ('serial', models.IntegerField(default=1)),
                ('credits', models.IntegerField(default=3)),
                ('coreqs', models.TextField(default='HELP-123')),
                ('prereqs', models.TextField(default='HELP-123')),
                ('sameAs', models.TextField(default='HELP-123')),
                ('countsAs', models.TextField(default='HELP-123')),
            ],
        ),
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1000)),
                ('building', models.TextField(default='ABC')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.TextField()),
                ('year', models.IntegerField(default=2018)),
                ('semester', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('currentlyEnrolled', models.IntegerField(default=0)),
                ('maxStudents', models.IntegerField(default=20)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
        migrations.AddField(
            model_name='days',
            name='times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
    ]
