# Generated by Django 2.1.3 on 2018-11-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='days',
            new_name='Day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coreqs',
        ),
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_coreqs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='countsAs',
            field=models.TextField(blank=True, default='HELP-123', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='idName',
            field=models.CharField(default='HELP-123', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Introduction to Django', max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.TextField(blank=True, default='HELP-123', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sameAs',
            field=models.TextField(blank=True, default='HELP-123', null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
    ]
