# Generated by Django 2.1.3 on 2018-11-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181111_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='_course_coreqs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='day',
            name='times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
    ]
