# Generated by Django 2.1.3 on 2018-11-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181111_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_coreqs_+', to='courses.Course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='countsAs',
        ),
        migrations.AddField(
            model_name='course',
            name='countsAs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_countsAs_+', to='courses.Course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_prereqs_+', to='courses.Course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='sameAs',
        ),
        migrations.AddField(
            model_name='course',
            name='sameAs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_sameAs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='day',
            name='times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
    ]
