# Generated by Django 2.1.3 on 2018-11-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181111_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='times',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rooms',
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Room'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='_course_coreqs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='countsAs',
            field=models.ManyToManyField(blank=True, related_name='_course_countsAs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sameAs',
            field=models.ManyToManyField(blank=True, related_name='_course_sameAs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(default='ABC', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='cost',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='section',
            name='maxStudents',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='serial',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='section',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Session'),
        ),
    ]
