# Generated by Django 2.1.3 on 2018-11-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181111_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Room')),
            ],
        ),
        migrations.RenameField(
            model_name='section',
            old_name='sessions',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='room',
            new_name='block',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='_course_coreqs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='countsAs',
            field=models.ManyToManyField(blank=True, related_name='_course_countsAs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sameAs',
            field=models.ManyToManyField(blank=True, related_name='_course_sameAs_+', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Room'),
        ),
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1),
        ),
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Session'),
        ),
    ]
